
server:
  port: 30501
  shutdown: graceful

logging:
  # logback 설정
  config: ./logback-spring.xml

spring:
  boot:
    admin:
      client:
        url: http://10.147.1.232:39000
        username: admin
        password: humusOn0722!
        instance:
          service-host-type: ip

  banner:
    location: classpath:banner.txt

  ## datasource
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://10.147.1.90:23306/cmc_api?characterEncoding=UTF-8
    username: imc-dev
    password: humuson0722
    hikari:
      maximum-pool-size: 20
      minimum-idle: 10
      connection-timeout: 60000

  ## JPA
  jpa:
    database: mysql
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        globally_quoted_identifiers: true
        globally_quoted_identifiers_skip_column_definitions: true
        query:
          in_clause_parameter_padding: true
    open-in-view: false

  ## redis
  redis:
    cluster:
      nodes:
        - 10.147.1.121:6379
        - 10.147.1.122:6380
        - 10.147.1.123:6381
    password: humuson0722
    timeout: 30s

## cmc email-control config
cmc:
  email:
    control:
      swagger:
        develop-url: "http://10.147.1.232:20000/email-control"
