server:
  port: 8080
  shutdown: graceful
  host: localhost
  netty:
    port: 30102
    boss-count: 1000
    worker-count: 1000
    keep-alive: TRUE
    backlog: 2024

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

